var imgArchLink = ["1747-H.Walpole-Strawberry Hill-Storicismi-interni.jpg", 
"1747-H.Walpole-Strawberry Hill-Storicismi.jpg", 
"1778-1784-C.N Ledoux- Teatro di Besacon-Storicismi-Sezione.jpg", 
"1778-1784-C.N Ledoux- Teatro di Besacon-Storicismi.jpg", 
"1784-E.L.Boulee-Cenotafio di Newton-Storicismi.jpg", 
"1791-J.Bentham-Panopticon or the inspection House-Storicismi.jpg", 
"1818-Robert Owen-Viallaggio di New Lanark-Città Industriale.jpg", 
"1823-1830-K.F Schinkel-altes museum-Storicismi.jpg", 
"1823-1830-K.F Schinkel-Sezione altes museum-Storicismi.jpg", 
"1829-C.Fourier-prospettiva di un falasterio dedicato a L'avenir -Città Industriali.jpg", 
"1830-1842-L. Von Klenze-Walhalla-Ratisbona-Storicismi.jpg", 
"1838-1850-H.Labrouste-Biblioteque Sainte Genevieve-Parigi-Arch Ferro e Vetro-Interni.jpg", 
"1838-1850-H.Labrouste-Biblioteque Sainte Genevieve-Parigi-Arch Ferro e Vetro.jpg", 
"1851-H.Roberts-Casa Modello per famiglie-Great Exhibition- Arc Ferro e Vetro.jpg", 
"1851-Joseph Paxton-Crystal Palace-Londra-Arc. Ferro e Vetro.jpeg", 
"1853-1867-H.Labrouste-Biblioteque Nationale-Parigi-Arch Ferro e Vetro-Interni.jpg", 
"1853-1867-H.Labrouste-Biblioteque Nationale-Parigi-Arch Ferro e Vetro.jpg", 
"1853-1889-F.Panciatichi Ximenes d'Aragona-Castello di Sammezzano-Leccio-Storicismi.jpg", 
"1853-T.Salt-Saltaire-Bradford-Città Industriali.jpg", 
"1856-1857-J.Bordagus-Edificio canal Street New York, Brevetto US 7337 (1850)- Nuovo Mondo.jpg", 
"1857-G.G. Scott-Progetto neogotico per il Foreign Office-Arch. Ferro e Vetro.jpg", 
"1859-1889-A.Antonelli-Mole Antonelliana-Torino-Arch. Ferro e Vetro.jpg", 
"1860-W. Morris, P.Webb-Red House piantina-Bexleyheath-Arts And Crafts.jpg", 
"1860-W. Morris, P.Webb-Red House-Bexleyheath-Arts And Crafts.jpg", 
"1861-1875-C.Garnier-Teatro dell'opera-Parigi-Arch. Ferro e Vetro-Foyer.jpg", 
"1861-1875-C.Garnier-Teatro dell'opera-Parigi-Arch. Ferro e Vetro-Sezione.jpg", 
"1861-1875-C.Garnier-Teatro dell'opera-Parigi-Arch. Ferro e Vetro.jpg", 
"1862-1873-G.G. Scott-Facciata della stazione st Pancras-Londra-Arch Ferro e Vetro.jpg", 
"1862-1873-W.H. Barlow-Interno stazione St. Pancras-Londra-Arch Ferro e Vetro.jpg", 
"1863-E.E. Viollet ble Duc-Mercato coperto con soprastante sala riunioni-Storicismi.jpg", 
"1863-F.Callet-Halles Centrales de Paris-Arch. Ferro e Vetro.jpg", 
"1865-1867-G.Mengoni-Galleria Vittorio Emanuele-Milano-Arch. Ferro e Vetro-Interni.jpg", 
"1865-1867-G.Mengoni-Galleria Vittorio Emanuele-Milano-Arch. Ferro e Vetro.jpg", 
"1865-1868-A.Mazzucchetti, C.Ceppi-Esterno Staz Porta Nuova-Torino-Arch. Ferro e Vetro.jpg", 
"1868-G.G. Scott-Foreign Office-Londra-Arch. Ferro e Vetro.jpg", 
"1869-1874-C.Boito-Ospedale di Gallarate-Milano-Storicismi.jpeg", 
"1870-C. Vaux, F.L Olmsted-Mappa di central Park-Nuovo mondo.jpg", 
"1874-1875-H.R. Richardson-Watts Sherman House, Newport-Nuovo Mondo.jpg", 
"1874-1888-G. Semper-Burgtheater-Vienna-Storicismi.jpg", 
"1874-R.Carnevari-Progetto del ministero delle Finanze a Roma-Storicismi.jpg", 
"1875-Carlo G.N. Leumann-Villaggio Leumann-Collegno-Torino-Città Industriali.jpg", 
"1876-G.Eiffel, L.C. Boileau-Magazzini-Bon Marche-Parigi-Arch. Ferro e Vetro.jpg", 
"1879-1881-W. Le Baron Jenney-First Leider Building, Chicago- Scuola di Chicago.jpg", 
"1883---A. Gaudì-Sagrada Familia, Barcellona-Art Nouveau.jpg", 
"1885-1887-H.H. Richardson-Marshall Fields Chicago-Scuola di Chicago.jpg", 
"1885-1888-G.Sacconi-Il Vittoriano-Roma-Storicismi.jpg", 
"1885-1890-Burnham e Root-Monadnok Building Chicago-Scuola di Chicago.jpg", 
"1886-1889-L.H. Sullivan, D. Adler-Auditorium Chicago-Scuola di Chicago.jpg", 
"1886-McKim, Mead, White-Low House (Rhode Island), Bristol-Nuovo Mondo.jpg", 
"1887-1895-McKim, Mead e White-Boston Library- Nuovo Mondo.jpg", 
"1889-1891-W.Le Baron Jenney-Manhattan Building Chicago-Scuola di Chicago.jpg", 
"1889-F.L Whright-Casa Studio a Oak Park-Nuovo Mondo.jpeg", 
"1889-Gustave Eiffel-Tour Eiffel-Arch. Ferro e Vetro.jpg", 
"1890-1892-D.Burnham-Masonic Temple, Chicago-Scuola di Chicago.jpg", 
"1891-1892-W. Le Baron Jenney-Fair Building Chicago-Scuola di Chicago.jpg", 
"1891-1896-L. Sullivan, D.Adler-Guaranty Building, Buffalo-Nuovo Mondo.jpg", 
"1893-1894-V.Horta-Maison Tassel, Bruxelles, scala-Art Nouveau.JPG", 
"1893-1894-V.Horta-Maison Tassel, Bruxelles-Art Nouveau.JPG", 
"1893-94-F.L.Wright-Winslow House, River Forest-Nuovo Mondo.jpg", 
"1893-P. Hankar-Casa Hankar, Bruxelles Saint-Gilles-Art Nouveau.jpg", 
"1895-1900-O. Wagner-Pavillon per la metropolitana di Vienna KARLSPLATZ-Art Nouveau.jpeg", 
"1895-1920-J.Puig Cadafalch-Caves Cordoniu, Saint Sadurnì d'Anonia-Art Nouveau.jpeg", 
"1897-1898-J.M.Olbrich-Padiglione della secessione Vienna, Tavola di Progetto-Art Nouveau.jpg", 
"1897-1898-J.M.Olbrich-Padiglione della secessione Vienna-Art Nouveau.jpg", 
"1897-1909-C.R. Mackintosh-School of Art, Glasgow, biblioteca-Art Nouveau.jpg", 
"1897-1909-C.R. Mackintosh-School of Art, Glasgow-Art Nouveau.jpg", 
"1898-1899-O. Wagner-Maiolika Haus, Vienna-Art Nouveau.jpg", 
"1898-1903-H. P. Berlage-Borsa di Amsterdam-Neoplasticismo Olandese.jpg", 
"1898-C.F.A. Voysey-Broad Leys House, Ghyll Head, Windermere-Arts and Crafts .jpg", 
"1898-E. Lutyens-Ovestand Hall. Norfolk,England-Arts And Crafts.jpg", 
"1898-E.Howard-Garden City-Città Industriali.jpg", 
"1898-E.Howard-The three magnets-Città Industriali.jpg", 
"1898-G.Klimt-Manifesto per la prima esposizione della secessione-Art Nouveau.jpeg", 
"1898-V.Horta-Maison Horta, Bruxelles-Art Nouveau.jpg", 
"1899-1900-E. Basile-Villa Igeia, Palermo, salone-Art Nouveau.jpg", 
"1899-1900-E. Basile-Villa Igeia, Palermo-Art Nouveau.jpg", 
"1899-1901-G. Metzendorf-Casa per Lavoratori,Darmstadt-Arts And Crafts.jpeg", 
"1899-1901-J. Olbrich-Villa Olbrich, Colonia degli Artisti, Darmstadt-Arts And Crafts.jpeg", 
"1899-1901-P. Behrens-Casa Behrens, Darmstadt-Arts And Crafts.jpg", 
"1899-A. Loos-Cafè Museum,Vienna, Interno-Teknè.jpg", 
"1900-1903-G. Sommaruga-Palazzo Castiglioni, Milano-Art Nouveau.jpg", 
"1900-1914-A. Gaudì-Parc Guell,Barcellona, passaggio coperto-Art Nouveau-1.jpg", 
"1900-1914-A. Gaudì-Parc Guell,Barcellona, passaggio coperto-Art Nouveau.jpg", 
"1900-H. Guimard-Stazioni della metropolitana, Parigi-Art Nouveau.JPG", 
"1900-K.F. Shinkel-Palazzo Redern-Berlino-Storicismi.jpg", 
"1901 Feb-A Home In A Prairie Town -Ladies Home Journal-Nuovo Mondo.jpg", 
"1901-E. Lutyens-Homewood, Hertforshire, pianta-Arts And Crafts .jpeg", 
"1901-E. Lutyens-Homewood, Hertforshire, prospetto laterale-Arts And Crafts .jpeg", 
"1901-H. Van De Velde-Scuola di arti e mestieri, Weimar-Art Nouveau.jpg", 
"1902-1903-F.L.Whright-Ward Willis House, Highland Park-Nuovo Mondo.jpeg", 
"1902-1904-C.R.Mackintosh-Hill House, Helensburg, destra-Art Nouveau.jpg", 
"1902-1904-C.R.Mackintosh-Hill House, Helensburg, tavola progetto (sx)-Art Nouveau.jpg", 
"1902-1905-G.B. Bossi-Casa Galimberti, Milano-Art Nouveau.jpg", 
"1902-L.Bistolfi-Manifesto Prima Esposizione internazionale d'Arte decorativa moderna Torino-Art Nouveau.jpeg", 
"1902-Le Corbusier-Cassa di orologio decorato, premiato all'eposizione internazionale di arti decorative di Torino-Movimento moderno-.jpg", 
"1902-P.Fenoglio-Villino Scott, Torino-Art Nouveau.jpg", 
"1902-R. D'Aronco-Prima Esposizione internazionale d'Arte decorativa moderna Torino, ingresso-Art Nouveau.jpeg", 
"1903-1905-C.R Mackintosh-Willow Tea Rooms, Glasgow-Art Nouveau.jpg", 
"1903-A.Perret-Edificio per abitazioni al 25bis di rue Fraklin,Parigi-Teknè.jpg", 
"1904-1907-A. Gaudì-Casa Battlò, Barcellona-Art Nouveau-1.jpg", 
"1904-1907-A. Gaudì-Casa Battlò, Barcellona-Art Nouveau.jpg", 
"1904-1912-O. Wagner-Sede della Kaiserlich Konigliche Postsparkasse, Georg Coch-Platz, Vienna-Art Nouveau.jpg", 
"1904-C. Voysey-Prior's Field. in Hermann Muthesius Das Englische Haus-Arts And Crafts.jpg", 
"1905-1908-F.L Wright-Unity Temple, Oak Park-Nuovo Mondo.jpg", 
"1905-1911-J. Hoffman-Palais Stoclet, Bruxelles, hall-Art Nouveau.jpg", 
"1905-1911-J. Hoffman-Palais Stoclet, Bruxelles, sala da pranzo-Art Nouveau.jpg", 
"1905-1911-J. Hoffman-Palais Stoclet, Bruxelles-Art Nouveau.jpg", 
"1905-1930-L. Domenech i Montaner-Ospedale Sant Pau-Barcellona-Art Nouveau.jpg", 
"1905-J.Puig i Cadafalch-Casa de les Punxes, Barcellona-Art Nouveau.jpeg", 
"1905-P. Fenoglio-Sede della fabbrica di cioccolato Venchi, Torino-Art Nouveau.jpg", 
"1906-1924-T.Garnier-Grande Halle del mercato del bestiame, Lione-Teknè-1.jpg", 
"1906-1924-T.Garnier-Grande Halle del mercato del bestiame, Lione-Teknè.jpg", 
"1907-Le Corbusier-Disegni dal carnet del viaggio in Itali-Movimento moderno.jpg", 
"1908-1910-F.L Wright-Robie House, Chicago, area pranzo-Nuovo Mondo-1.jpg", 
"1908-1910-F.L Wright-Robie House, Chicago, area pranzo-Nuovo Mondo.jpg", 
"1908-1910-F.L Wright-Robie House, Chicago, soggiorno-Nuovo Mondo.jpg", 
"1908-1910-F.L Wright-Robie House, Chicago-Nuovo Mondo.jpg", 
"1908-1910-P.Behrens-AEG Fabbrica turbine, interno-Arts And Crafts.jpg", 
"1908-1910-P.Behrens-AEG Fabbrica turbine-Arts And Crafts.jpg", 
"1909-1923-R. Ostberg-Municipio di stoccolma-Teknè.jpeg", 
"1909-D. Burnham-Civic Center Plaza, Piano per Chicago-Scuola di Chicago.jpg", 
"1910-A.Loos-Casa in Michaelerplatz, Vienna-Teknè.jpg", 
"1910-A.Loos-Casa in Michaelerplatz,interni, Vienna-Teknè.jpg", 
"1910-A.Loos-Casa Steiner,Vienna 2-Teknè.jpg", 
"1910-A.Loos-Casa Steiner,Vienna-Teknè.jpeg", 
"1910-H. Poelzig-Torre dell'acqua,Posen-Arts And Crafts.jpg", 
"1910-R. Riemerschmid-Hellerau Dresden-Arts And Crafts.jpg", 
"1911-W.Gropius, A. Meyer-Officine Fagus, Alfeld-Movimento moderno.jpg", 
"1912-1913-A.Loos-Casa Scheu, Vienna, pianta-Teknè.jpg", 
"1912-1913-A.Loos-Casa Scheu, Vienna-Teknè.jpg", 
"1912-H. Sauvage, C. Sarazin-Edificio al 26 di Rue Vavin, Parigi-Teknè.jpg", 
"1913-1919-M. De Klerk-Spandammerbuurt, Amsterdam-Movimento Moderno.jpeg", 
"1913-R.Steiner-Primo Goetheanum, Dornach (distrutto 1922)-Espressionismo Tedesco.jpg", 
"1914-1915-Le corbusier-Maison Dom-ino,disegno-Movimento moderno.jpeg", 
"1914-1919-R. Vant'Hoff-Villa Henny, Ultrecht-Neoplasticismo Olandese.jpg", 
"1914-A. Sant'elia-Architettura futurista, Manifesto-Futurismo.JPG", 
"1914-A. Sant'elia-Centrale Elettrica-Futurismo.jpg", 
"1914-A. Sant'Elia-Città Nuova-Futurismo.jpg", 
"1914-B.Taut-Padiglione del vetro, Esposizione di Colonia-Espressionismo Tedesco.jpg", 
"1914-H.Van De Velde-Teatro dell'esposizione del Deutscher Werkbund, Colonia, Pianta-Arts And Crafts.jpeg", 
"1914-H.Van De Velde-Teatro dell'esposizione del Deutscher Werkbund, Colonia-Arts And Crafts.jpg", 
"1914-P.Berhens-Festhalle,Colonia-Arts And Crafts.jpg", 
"1915-1922-G.Mattè-Trucco-Stabilimento Fiat Lingotto, Torino, veduta del 1926-Teknè.jpeg", 
"1916-1922-H. Sauvage-Edificio in rue Des Amiraux, sezione trasversale-Teknè.jpg", 
"1916-Le Corbusier-Villa Schwob, Le Chaux-de-fonds-Movimento moderno.jpg", 
"1917-1921-E. Mendelsohn-Osservatorio Atronomico Albert Einstein, Potsdam-Espressionismo tedesco.jpg", 
"1917-1933-T. Garnier-Quartiere Etats-Units, gli isolati e i passaggi comunitari, Lione-Teknè.jpg", 
"1917-T. Garnier-Citè Industrielle, fabbrica metallurgica-Teknè.jpg", 
"1917-T. Garnier-Citè Industrielle, residenze-Teknè.jpg", 
"1917-T. Garnier-Citè Industrielle, stazione dei bus-Teknè.jpg", 
"1917-T. Garnier-Citè Industrielle, villa d'artista-Teknè.jpg", 
"1917-T. Garnier-Citè Industrielle-Teknè.jpg", 
"1918-1919-H.Poelzig-Grosses Schauspielhaus, Berlino, distrutto nel 1988-Espressionismo tedesco.jpeg", 
"1918-1920-G.Aplund-Wood Church, cimitero Enskede,Stoccolma-Teknè.jpeg", 
"1918-1923-P.Kramer-De Dageraad, Amsterdam-Movimento Moderno.jpg", 
"1919-1921-M. Brinkman-Blocco Residenziale, Spangen, Rotterdam-Movimento Moderno.jpg", 
"1919-1923-G.Muzio-Ca'Brutta, Milano-Totalitarismi.JPG", 
"1919-A.Perret-Sartoria Henri Esdier, Parigi-Teknè.jpg", 
"1920-1921-W.Gropius, A. Meyer-Casa Sommerfeld, Berlino, Dalhem-Movimento moderno.jpg", 
"1920-1928-G.Aplund-Biblioteca civica di Stoccolma-Teknè.jpg", 
"1920-L. El Lissitzky-Tribuna Lenin,Progetto-Costruttivismo Russo.jpeg", 
"1921-1922-L. Mies Van de Rohe-Grattacielo in vetro, progetto-Movimento moderno.jpg", 
"1921-1928-J.B. Van Loghem-Betondorp, Amsterdam-Movimento Moderno.jpeg", 
"1921-T.Garnier-quartiere Etats-unis, in Grand Travaux-Teknè.jpg", 
"1922-1923-A.Perret-Chiesa di Notre-Dame, Raincy, interno-Teknè.jpg", 
"1922-A.Loos-Progetto per il concorso della sede del Chicago Tribune-Teknè.jpg", 
"1922-Le Corbusier-Une Ville contemporaine-Movimento moderno.jpg", 
"1922-W. Gropius-Concorso Internazionale per il Chicago Tribune, progetto-Movimento moderno.jpg", 
"1922-W.Gropius-Monumento ai caduti di Marzo, Weimar-Movimento moderno.jpg", 
"1923-1924-G.T Rietveld-Casa Schroder-Schrader, Ultrecht-Neoplasticismo Olandese.jpg", 
"1923-1924-G.T Rietveld-Casa Schroder-Schrader,piante, Ultrecht-Neoplasticismo Olandese.jpg", 
"1923-1928-R.Steiner-Secondo Goetheanum, Dornach-Espressionismo Tedesco.jpg", 
"1923-E.Maigrot-Mercati Generali, Torino, interni-Teknè.jpg", 
"1923-F.Hoger-Chilehaus, Amburgo-Espressionismo tedesco.jpg", 
"1923-G. Muche-Casa am Horn,Weimar-Movimento moderno.jpg", 
"1924-1927-J.J.P. Oud-Hoek van Holland, Rotterdam-Movimento Moderno.jpg", 
"1924-1929-A.Aalto-Associazione regionale patrioti, Seinajoki-Teknè.jpg", 
"1924-A.Aalto-Club lavoratori, Jyvaskyla-Teknè.jpeg", 
"1924-O.Haesier-Georgsgarten,Celle-Movimento moderno.jpg", 
"1925 Parigi-1977Bologna-Le Corbusier-Padiglione dell'esprit Nouveau-Movimento moderno.jpg", 
"1925-1926-P.Engelmann L.Wittgenstein,Vienna, pianta-Teknè.jpg", 
"1925-1926-P.Engelmann L.Wittgenstein,Vienna-Teknè.jpg", 
"1925-1926-R. Perco, R. Frass e K. Dorfmeister-Professor Jodi Hof, Vienna-Movimento Moderno.jpg", 
"1925-1926-W.Gropius-Bauhaus,Dessau-Movimento moderno.jpg", 
"1925-1933-B.Taut-Hufeisen Siedlung, complesso residenziale, Berlino Britz, panimetria-Movimento moderno.jpg", 
"1925-1933-B.Taut-Hufeisen Siedlung, complesso residenziale, Berlino Britz-Movimento moderno.jpg", 
"1925-1985-J.J.P. Oud-Cafè De Unie,Rotterdam-Neoplasticismo Olandese.jpg", 
"1925-L. El Lissitzky-Grattacieli Orizzontali, Progetto-Costruttivismo russo.jpeg", 
"1925-L.Mies Van de Rohe-Monumento a Karl Liebknecht a Rosa Luxemburg, Berlino (demolito 1933)-Movimento moderno.jpeg", 
"1925-Le Corbusier-Quartiere operaio, Pessac-Movimento moderno.JPG", 
"1925-V. Tatlin-Monumento alla Terza Internazionale (1919-1920), modello, Mosca-Costruttivismo Russo.jpg", 
"1926-1927-A.Loos-Casa Moller, Vienna, pianta-Teknè.jpg", 
"1926-1927-A.Loos-Casa Moller, Vienna-Teknè.jpg", 
"1926-1927-E. May-Bruchfeldstrasse, Francoforte-Movimento Moderno.jpg", 
"1926-1927-H. Schmid, H. Aichinger-Matteotti Hof, Vienna-Movimento Moderno.jpeg", 
"1926-1928-W. Gropius-Quartiere Torten, Dessau-Movimento moderno.jpg", 
"1926-1931-A.Mazzoni-Colonia marina a Calambrone (Pisa)-Totalitarismi.jpg", 
"1926-R.Owen-New Harmony-Indiana-Città Industriali.jpg", 
"1927-1929-E.May-Romerstadt, Francoforte-Movimento Moderno.JPG", 
"1927-1929-G.Terragni-Novocomum, Como-Totalitarismi.jpg", 
"1927-1929-K. Melnikov, Club Rusakov, Mosca-Costruttivismo Russo.jpg", 
"1927-1929-K.Melnikov-Casa Cilindrica, Mosca-Costruttivismo Russo.jpg", 
"1927-1930-K. Krist e R. Oerley-George Washington-Hof, Vienna-Movimento Moderno.jpg", 
"1927-1930-K.Ehn-Karl Marx Hof, Vienna-Movimento Moderno.JPG", 
"1927-1935-A. aalto-Biblioteca di Viipuri, sezione-Teknè.jpg", 
"1927-1935-A. aalto-Biblioteca di Viipuri, vista sala per riunioni-Teknè.jpeg", 
"1927-1938-Y. Shchuko, V.G. Gel'freikh-Biblioteca Lenin, Mosca-Totalitarismi.jpg", 
"1927-F. Deplero-Padiglione -Tipografico- III Biennale di Monza-Futurismo.jpg", 
"1927-H. Scharoun-Casa Unifamiliare al Weissenhof, Stoccarda-Espressionismo Tedesco.jpeg", 
"1927-J.J.P.Oud-Prototipo case a schiera, Stoccarda-Movimento Moderno.jpg", 
"1927-L.Mies Van De Rohe-Esposizione del Weissenhof Siedlung, Stoccarda-Movimento moderno.jpeg", 
"1927-Le Corbusier-Casa per il Weissenhof, Stoccarda-Movimento moderno.jpeg", 
"1927-Le Corbusier-Concorso internazionale per il palazzo della società delle nazioni di Ginevra, progetto-Movimento moderno.jpg", 
"1927-W. Gropius-Total-Theater, progetto-Movimento moderno.jpg", 
"1928-1930-G.Pagano, G. Levi-Montalcini-Palazzo per uffici Gualino, Torino-Totalitarismi.jpg", 
"1928-1930-M.Ginzburg, I. Milinis-Narkomfin (comissariato del popolo per le finanze),Mosca-Costruttivismo Russo.jpg", 
"1928-1989-T. van Doesburg-Cafè L'Aubette, Strabusrgo-Neoplasticismo Olandese.jpeg", 
"1928-A. Sartoris-Padiglione delle Comunità Artigiane, Esposizione Nazionale di Torino 1928-Futurismo.jpg", 
"1928-A.Klein-Studi per progetto razionale dell'alloggio minimo-Movimento moderno.jpg", 
"1928-E. Prampolini-Padiglione del futurismo, Esposizione Nazionale di Torino 1928-Futurismo.jpeg", 
"1928-I. Golosov-Club Zuev, Mosca-Costruttivismo Russo.jpg", 
"1929-1931-A. Lurcat-Hotel Nord-Sud, Calvi, Corsica-Movimento Moderno.jpg", 
"1929-1931-G.Pagano, G. Levi-Montalcini-Villa Colli a Rivara Canavese, Torino-Totalitarismi.jpg", 
"1929-1931-H. Scharoun-Siemensstadt,Berlino-Movimento moderno.jpeg", 
"1929-1931-Le Corbusier-Villa Savoye, Poissy-Movimento moderno.jpg", 
"1929-1931-W.Gropius et alii-Siemensstadt, Berlino, modello-Movimento moderno.jpg", 
"1929-1933-A. Aalto-Sanatorio di Paimio, balconata sulla copertura del corpo di degenza-Teknè.jpeg", 
"1929-1933-A. Aalto-Sanatorio di Paimio, stanza di degenza-Teknè.jpeg", 
"1929-1933-A. Aalto-Sanatorio di Paimio-Teknè.jpg", 
"1929-A. Scusev-Mausoleo di Lenin, Mosca-Totalitarismi.jpg", 
"1929-L. Mies Van De Rohe-Padiglione della Germania, Esposizione Universale di Barcellona (ricostruito nel 1986), pianta-Movimento moderno.jpg", 
"1929-L. Mies Van De Rohe-Padiglione della Germania, Esposizione Universale di Barcellona (ricostruito nel 1986)-Movimento moderno.jpeg", 
"1929-Le Corbusier-Citè de Refuge, Parigi-Movimento moderno.jpg", 
"1929-Le Corbusier-Palazzo del centro Soyus, Mosca-Movimento moderno.png", 
"1930-1932-A.Loos-Casa alla Werkbund Siedlung,Vienna-Teknè.JPG", 
"1930-1933-B. Jofan-Palazzo dei Soviet,Concorso-Costruttivismo Russo.jpg", 
"1930-1933-P.L.Nervi-Scala Eloicodale dello stadio Berta, Firenze-Teknè.jpg", 
"1930-1936-E. Del Debbio-Foro Italico, Stadio dei Marmi, Roma-Totalitarismi.jpg", 
"1930-L.Mies Van De Rohe-Villa Tugendhat,Brno, planimetrie-Movimento moderno.jpg", 
"1930-L.Mies Van De Rohe-Villa Tugendhat,Brno, zona pranzo-Movimento moderno.jpeg", 
"1930-L.Mies Van De Rohe-Villa Tugendhat,Brno-Movimento moderno.jpg", 
"1931-A. Aalto-Poltrona Paiomio-Teknè.jpg", 
"1932-1935-M.Piacentini-Città Universitaria di Roma-Totalitarismi.jpg", 
"1932-1936-G.Vaccaro,G.Franzi-Palazzo delle poste, Napoli-Totalitarismi.jpg", 
"1932-G.Terragni-Casa del Fascio-Totalitarismi.jpg", 
"1933-1934-A. Libera,M. De Renzi-Palazzo delle poste, Roma-Totalitarismi.jpg", 
"1933-1935-G. Terragni-Casa Rustici (Con Lingeri), Milano-Totalitarismi.jpg", 
"1933-1936-M. Piacentini-Ricostruzione del secondo tratto di via Roma, Torino-Totalitarismi.jpg", 
"1933-1937-P.L. Troost-Haus der Kunst (casa dell'arte),Monaco-Totalitarismi.jpeg", 
"1933-1941-M. Piacentini-Palazzo di giustizia, Milano-Totalitarismi.jpg", 
"1933-G. Pagano (Con Albini,Camus,Mazzoleni,Minoletti,Palanti)-Casa e struttura in acciaio per la V triennale di Milano-Totalitarismi.jpg", 
"1933-G.Michelucci-Stazione di Santa Maria Novella, Firenze-Totalitarismi.jpg", 
"1934-1937-A.Speer-Zeppelinfeld, Norimberga-Totalitarismi.jpg", 
"1934-1940-K. Alabyan, V. Simbirtsev-Teatro dell'armata Rossa, Mosca-Totalitarismi.jpg", 
"1934-C.Busiri-Vici-Colonia marina a Cattolica(Forlì)-Totalitarismi.jpg", 
"1935-1938-I. Gradella-Dispensario antitubercolare, Alessandria-Totalitarismi.jpeg", 
"1935-Le Corbusier-Ville Radieuse, modello-Movimento moderno.jpg", 
"1935-P.L.Troost-Ehrentempel (Templi dei martiri), Monaco-Totalitarismi.jpg", 
"1936-1940-C. Mollino-Società ippica, Torinese-Totalitarismi.jpg", 
"1936-A. Speer-L'Olympiastadium (Stadio Olimpico), Berlino-Totalitarismi.jpg", 
"1937-1940-G.Guerrini, E. La Padula, M. Romano-Palazzo della civiltà italiana all'E42, Roma-Totalitarismi.jpg", 
"1937-1941-G.Pagano, G.G.Predaval-Sede dell'università Bocconi, Milano-Totalitarismi.jpeg", 
"1937-1954-A.Libera-Palazzo dei Congressi all'E42, Roma-Totalitarismi.jpg", 
"1937-A. Speer-Padiglione della germania all'esposizione universale di Parigi-Totalitarismi.jpg", 
"1937-B. Iofan-Padiglione sovietico all'esposizione di Parigi-Totalitarismi.jpg", 
"1938-1939-A. Aalto-Villa Mairea, Noormakku, interno della sala al pian terreno-Teknè.jpg", 
"1938-1939-A. Aalto-Villa Mairea, Noormakku, vista sul giardino-Teknè.jpg", 
"1938-1939-A. Aalto-Villa Mairea, Noormakku-Teknè.jpg", 
"1938-I. Guidi, E. Montuori, C. Valle-Carboni, vista-Totalitarismi.jpg", 
"1938-W. Gropius-Casa Gropius, Lincoln (massachussets)-Movimento moderno.jpg", 
"1939-A. Speer-Grosse Halle, Modello-Totalitarismi.jpg", 
"1939-A.Speer-Modello della nuova Berlino, voluta da Hitler-Totalitarismi.jpeg", 
"1939-A.Speer-Nuova Cancelleria, Berlino-Totalitarismi.jpg", 
"1939-G. Quaroni-Manifesto Ufficiale dell'esposizione universale-Totalitarismi.jpeg", 
"1942-1947-Le Corbusier-Modulor-Movimento moderno.jpg", 
"1950-1956-A. Mordinov-Hotel Ucraina, Mosca-Totalitarismi.jpg", 
"1950-M. Nizzoli-Macchina da scrivere Lettera 22-Totalitarismi.jpeg", 
"W.Gropius, A.Meyer-Edificio Industriale modello, mostra del Werkbund, Colonia-Movimento moderno.jpg" ];

var imgDesLink =["-diesgno di Hoffmann-Sala Cabaret Fledermaus-Art Déco.jpeg", 
"-F. jourdain e M.Sauvage-Magazzini Samaritaine-Art Déco.jpeg", 
"-J. E. Ruhlmann-Poltrona-Art Déco.jpeg", 
"-J. H. Ruhlmann-Mobiletto in ebano tartaruga e avorio-Art Déco.jpeg", 
"-N.B. Geddes-diagramma illustrativo dei principi della progettazione aerodinamica-Streamlining.jpg", 
"-P. Iribe-piccola commode in zigrino ed Ebano-Art Déco.jpeg", 
"1768 (fondata società) Wedgewood-Josiah Wedgewood-Fabbrica Etruria sul canale Trent-Mersey-Rivoluzione Industriale.jpg", 
"1775-J. Flaxman-Brocche di basalto nero disegnate per Wedgwood-Rivoluzione Industriale.jpeg", 
"1777-Thomas T.Pritchard-Ponte sul fiume Evern-Coalbrookdale-Rivoluzione Industriale.jpeg", 
"1793-J.Wedgewood-Riproduzione vaso Portland-Rivoluzione Industriale 2.jpg", 
"1793-J.Wedgewood-Riproduzione vaso Portland-Rivoluzione Industriale.jpg", 
"1839-Macchina per Dagherrotipi.jpg", 
"1846-Mietritrice Virginia-McCormick-età vittoriana.jpg", 
"1850 circa-consolle modello 8803 thonet-età vittoriana.jpg", 
"1850 circa-Disegno di E. Mandl della poltrona Thonet N°14-età vittoriana.jpg", 
"1850 circa-poltrona a dondolo thonet-età vittoriana.jpg", 
"1850 circa-Thonet- Letto modello 9711-età vittoriana.jpg", 
"1851-Frontespizio del catalogo della Great Exhibition-Età Vittoriana.jpg", 
"1851-J. Paxton-Crystal Palace prospettiva del transetto-Età Vittoriana.jpg", 
"1851-J. Paxton-Crystal Palace-Età Vittoriana.jpeg", 
"1858-T. T. Woodruf-Vagone ferroviario con sedili a doppio ordine di cuccette-età vittoriana.jpg", 
"1859-Catalogo Gebruder Thonet-Età Vittoriana.jpg", 
"1865-Modello macchina da Cucire Singer.jpeg", 
"1871-G.Wilson-Poltrona regolabile-età vittoriana .jpg", 
"1871-W. Morris-Bedroom-Kelmscott Manor-Età Vittoriana.jpeg", 
"1873-Catalogo Gebruder Thonet-Età Vittoriana.jpg", 
"1877-W.Morris-Carta da parati Sunflower-età vittoriana 2.jpg", 
"1877-W.Morris-Carta da parati Sunflower-età vittoriana.jpg", 
"1879-Bicicletta.jpg", 
"1879-Edison-Lampadina.jpeg", 
"1880-Cruto-Lampadina.jpeg", 
"1884-1886-Thonet-Sedia N°14-Età Vittoriana.jpg", 
"1884-W. Morris-The principles of Socialism Frontespizio-Età Vittoriana-.jpeg", 
"1885-Benz-Automobile-.jpg", 
"1889-Daimler-Veicolo Sperimentale-.jpg", 
"1893-Benz-Automobile.jpg", 
"1897-1898-H.Van. de Velde-Scrivania-Età Vittoriana.jpg", 
"1904-J. Hoffmann-Posate in Argento-Wiener Werkstatte.jpg", 
"1905-Carl Otto Czeschka-Collier-Wiener Werkstatte.jpeg", 
"1905-J. Hoffmann-sedia a dondolo (produzione Kolu)-Wiener Werkstatte.jpeg", 
"1905-J. Hoffmann-sedia cabaret Fledermaus-Wiener Werkstatte.jpeg", 
"1905-J. Hoffmann-sedia sanatorio di Purkersdorf-Wiener Werkstatte.jpeg", 
"1907-Peter Berhens-Manifesto per la lampadina a filamento metallico-AEG.jpeg", 
"1908-Coperina Opuscolo AEG all_esposizione delle costruzioni navali tedesche-AEG.jpeg", 
"1908-J. Hoffmann-Poltrona con schienale Reclinabile (produzione Kolu)-Wiener Werkstatte.jpeg.jpg", 
"1908-Lampada ad arco a fiamma-AEG.jpg", 
"1908-Peter Berhens-Copertina catalogo di lampade ad arco-AEG.jpeg", 
"1908-Peter Berhens-Illustrazione per lampade a filamento metallico con logotipo esagonale-AEG.jpg", 
"1908-Ventilatore da tavolo-AEG.jpeg", 
"1909-11-Opuscolo per Riflettori-AEG.jpg", 
"1909-Fratelli Wright-Aereoplano.jpg", 
"1909-Peter Berhens-Teiera, bollitore elettrica-AEG.jpg", 
"1910-L. Bakst-Costumi per l_uccello di fuoco di Stravinskij-Art Déco.jpeg", 
"1910-P. Follot-Sedia per toilette-Art Déco.jpeg", 
"1912-L. Bakst-Costumi per balletto Dafni e Cloe di Ravel-Art Déco.jpeg", 
"1912-Logotipo del Werkbund Jahrbucher-Deutscher Werkbund.jpg", 
"1913-Ford Modello T (Thin Lizzy)-USA.jpeg", 
"1913-Ford Modello T Sportiva-USA.jpeg", 
"1914-K. Klint-Poltroncina rotonda con Paglia di Vienna-Design Scandinavo.jpeg", 
"1914-Manifesto Esposizione Deutscher Werkbund a Colonia-Deutscher Werkbund.jpg", 
"1918-G. T. Rietveld-Sedia Rosso-Blu-Neoplasticismo.jpeg", 
"1922-M. Breuer-Sedia con Braccioli-Bauhaus.jpg", 
"1923-K. J. Jucker e W. Wagenfeld-lampada da tavolo-Bauhaus.jpeg", 
"1923-K. J. Jucker-lampada elettrica da parete-Bauhaus.jpeg", 
"1924-M. Brandt-Servizio da thè-Bauhaus.jpg", 
"1924-M. Brandt-Teiera-Bauhaus.jpg", 
"1924-Otto Rittweger-servizio da thè-Bauhaus.jpg", 
"1925-A. Laprade-Padiglione grandi magazzini del Louvre all_Expo-Art Déco.jpg", 
"1925-Dominique-Sedia Imbottita-Art Déco.jpeg", 
"1925-J. E. Ruhlmann-Poltrona-Art Déco.jpeg", 
"1925-L.M. Boileau-Padiglione granfi magazzini Au Bon Marché all_Expo-Art Déco.jpg", 
"1925-Le Corbusier-Interno padiglione l_esprit Nouveau-Movimento Moderno.jpeg", 
"1925-Le Corbusier-padiglione l_esprit Nouveau-Movimento Moderno.jpeg", 
"1925-M. Breuer-Poltrona Wassily-Bauhaus.jpg", 
"1926-M. Brandt e H. Przyembel-Lampada saliscendi-Bauhaus.jpg", 
"1926-M. Stam-primo modello sedia a sbalzo-Bauhaus.jpg", 
"1927-Ford Modello A-USA.jpeg", 
"1927-G. Schutte Lihotzky-Cucina di Francoforte-International Style.jpeg", 
"1927-G. Stolzl-Arazzo-Bauhaus.jpeg", 
"1927-M. Brandt-Lampada da notte Kandem-Bauhaus.jpg", 
"1927-M. Brandt-Lampada snodabile da parete-Bauhaus.jpg", 
"1927-Mies Van Der Rohe-Sedia presentata al weissenhof di Stoccarda (solo la struttura)-Bauhaus.jpeg", 
"1928-Le Corbusier-Chaise Longue à Réglage continue (riedizione Cassina 1974)-Movimento Moderno.jpeg", 
"1928-Le Corbusier-Fauteuil grand confort (prototipo sperimentale)-Movimento Moderno.jpeg", 
"1928-Le Corbusier-Fauteuil grand confort (riedizione Cassina 1974)-Movimento Moderno.jpg", 
"1928-Le Corbusier-poltrona a schienale basculante (riedizione Cassina 1974)-Movimento Moderno.jpeg", 
"1928-M. Breuer-Sedia a sbalzo con schienale e sedile in tela-Bauhaus.jpg", 
"1928-M. Breuer-Sedia a sbalzo integrata da telai in legno e vimini intrecciati-Bauhaus.jpg", 
"1929-Mies Van Der Rohe-Poltrona Barcellona-Bauhaus.jpeg", 
"1930-35-A. Aalto-sgabelli per la biblioteca di Viipuri-Design Scandinavo.jpeg", 
"1930-A. E. Palmer-Auto disegnata per Sir D. Burney-Streamlining.jpeg", 
"1932-N. B. Geddes-idrovolante streamlined-Streamlining.jpeg", 
"1933-K. Klint-poltrona da riposo per navi-Design Scandinavo.jpeg", 
"1933-K. Klint-poltroncina smontabile safari-Design Scandinavo.jpeg", 
"1934-Chrysler Airflow-Streamlining.jpeg", 
"1935-Dc-3 della Douglas-Streamlining.jpeg", 
"1935-Fiat 1500-Streamlining.jpeg", 
"1936-A. Aalto-vasi Savoy-Design Scandinavo.jpg", 
"1936-Fiat 500-Streamlining.jpeg", 
"1936-W. D. Teague-fotocamera Kodak-Streamlining.jpeg", 
"1937-B. Mathsson-Poltrona della serie Pernilla-Design Scandinavo.jpeg", 
"1937-B. Mathsson-Poltroncina della serie Pernilla-Design Scandinavo.jpeg", 
"1937-F. Porsche-Volkswagen-Streamlining.jpeg", 
"1937-G. Jensen-Apparecchio per la Bell Telephones Company-Streamlining.jpeg", 
"1937-R. Loewy-locomotiva per la Pennsylvania Railroad-Streamlining.jpeg", 
"1938-H. Dreyfuss-Locomotiva per la New York Central System-Streamlining.jpeg", 
"1938-Tatra V-8-Streamlining.jpg", 
"1939-A. Aalto-Poltrona in legno curvato con fasce di tessuto-Design Scandinavo.jpeg", 
"1940-Ch. Eames e E. Saarinen-Poltrona disegnata per il concorso Organic Design In Home Furnishing del MOMA-Furniture Design.jpeg", 
"1945-B. Mogensen-Sofà per due persone-Design Scandinavo.jpeg", 
"1946-Charles Eames-sedia-Furniture Design.jpg", 
"1946-Eero Saarinen-Poltrona della serie a calice-Furniture Design.jpeg", 
"1948-1951-Charles Eames-Wire chair in metal mesh vista dall_alto-Furniture Design.jpg", 
"1948-1951-Charles Eames-Wire chair in metal mesh-Furniture Design.jpg", 
"1948-Eero Saarinen-Poltrona Imbottita e Sgabello-Furniture Design.jpeg", 
"1948-Eero Saarinen-Poltrona-Vasca-Furniture Design.jpeg", 
"1950-Charles Eames-Poltroncina-Furniture Design.jpg", 
"1950-P. Hvidt e O. Molgaard-Nielsen-AX Chair-Design Scandinavo.jpeg", 
"1951-1962-A. Aalto-Lampade Prodotte tra (data) 1-Design Scandinavo.jpeg", 
"1951-1962-A. Aalto-Lampade Prodotte tra (data) 3-Design Scandinavo.jpeg", 
"1951-1962-A. Aalto-Lampade Prodotte tra (data) 4-Design Scandinavo.jpg", 
"1951-1962-A. Aalto-Lampade Prodotte tra (data) 5-Design Scandinavo.jpeg", 
"1951-1962-A. Aalto-Lampade Prodotte tra (data) 6-Design Scandinavo.jpeg", 
"1951-F. Juhl-Poltroncina-Design Scandinavo.jpg", 
"1952-H. Bertoia-Diamond Chair-Furniture Design.jpeg", 
"1954-A. Aalto-Maniglie utilizzate nell_edificio Rautatalo-Design Scandinavo.jpg", 
"1954-A. Aalto-Sgabello-Design Scandinavo.jpeg", 
"1955-H. J. Wegner-Tavolo e sedia a tre gambe-Design Scandinavo.jpeg", 
"1957-A. Jacobsen-Sedia a tre gambe-Design Scandinavo.jpeg", 
"1957-Charles Eames-Upholstored Longue Chair and Ottoman-Furniture Design.jpg", 
"1957-F. Knoll-arredamento della sala di ricevimento negli uffici della Connecticut General Life Insurance Compagny a Bloomfield-Furniture Design .jpeg", 
"1958-Charles Eames-Poltrona con struttura in Alluminio-Furniture Design.jpg", 
"1958-Charles Eames-Sedia con struttura in Alluminio-Furniture Design.jpg", 
"1958-F. Juhl-Poltrona-Design Scandinavo.jpg", 
"1959-N. Roericht-Vasellame (tesi di laurea)-HFG di Ulm .jpeg", 
"1960-V. Panton-Sedia a S-Furniture Design.jpeg", 
"1962-T. Scarpa-Divano Bastiano-Furniture Design.jpeg", 
"1962-T. Scarpa-Poltrona Bastiano-Furniture Design.jpeg", ];

var imgGrafLink =["1475-Marchio-William Caxton.jpg", 
"1702-Costruzione di Lettere Romain du Roi-Louis Simoneau.jpeg", 
"1736-42-Incisione Petit Canon-Pierre Simon Fournier.png", 
"1751-Tavola dell_encyclopedie-.jpg", 
"1792-Manifesto pubblicitario per il Bulletin des Amis de la Veritè.jpg", 
"1818-Frontespizio del Manuale Tipografico-Giambattista Bodoni.jpg", 
"1840-Incisione per I Promessi Sposi-Francesco Gonin.jpeg", 
"1856-Foglie di Ippocastano. studio di composizione naturalistica-Owen Jones-Arts And cRAFTS.jpeg", 
"1860-Ripresa durante la guerra civile americana-Matthew Brady-Fotografia.jpg", 
"1860ca-Veduta di Firenze-Fratelli Alinari-Fotografia.jpg", 
"1861-Veduta delle fogne di Parigi-Felix Nadar-Fotografia.jpg", 
"1862-Copertina di Libro-Christopher Dresser-Art And Crafts.jpg", 
"1865-Illustrazione dal volume Alice in Wonderland-Lewis Carroll.jpg", 
"1865ca-Felix Nadar a bordo navicella del suo pallone a gas-Fotografia.jpg", 
"1868-Manifesto-Edouard Manet-Art Nouveau.jpg", 
"1871-Studi per Bordure-William Morris-Arts And Crafts.jpg", 
"1872ca-Varie fasi del movimento del cavallo-EadWeard MuyBridge-Fotografia.jpg", 
"1874-Frontespizio-Morris-Arts And Crafts.jpg", 
"1875-Manifesto per Grande magazzino-C.R. Franck.jpg", 
"1875-Manifesto per un circo-Jules Cheret-Art Nouveau.jpeg", 
"1882ca-Particolare stipo intagliato-Arthur Mackmurdo-Art Nouveau.jpg", 
"1883-Frontespizio per le chiese londinesi di Wren-Mackmurdo-Arts And Crafts.jpg", 
"1884-Frontespizio Historie des Quatre Fils Aymon-Eugène Grasset-Art Nouveau.jpg", 
"1884-pagina interna Historie des Quatre Fils Aymon-Eugène Grasset-Art Nouveau.jpg", 
"1886-Intervista di Felix Nadar allo scienziato Chevreul per la rivista Le Journal Illustré-Rivista Moderna.jpeg", 
"1888ca-Studio di figure in movimento-Etienne-Jules Marey-Fotografia.jpg", 
"1889-Manifesto per Jane Avril-Henri Toulose Lautrec-Art Nouveau.jpeg", 
"1891-Moulin Rouge-Henri Toulouse Lautrec-Art Nouveau.jpeg", 
"1892-Aristide Bruant-Henri Toulouse Lautrec-Art Nouveau.jpeg", 
"1892-Frontespizio e dorso per i poemi di Oscar Wilde-Charles Ricketts-Art Nouveau.jpg", 
"1892-Frontespizio News From Nowhere-William Morris-Arts And Crafts.jpg", 
"1892-Olympia-Jules Cheret-Art Nouveau.jpg", 
"1892-Progetto Carattere Troy-sotto-1891-Particolare libro The Story Of Glittering Plain-Morris-Arts And Crafts.jpg", 
"1892-Progetto Frontespizio-William Morris-Arts and Crafts.jpg", 
"1892-Pubblicità per L_Encre Marquet-Eugène Grasset-Art Nouveau.jpg", 
"1893-Copertina per The Studio-Aubrey Beardsley-Art Nouveau.jpeg", 
"1893-Copertina per Utopia di Tommaso Moro-James Cobden Sanderson-Arts And Crafts.jpg", 
"1893-Folies Bergère-Jules Cheret-Art Nouveau.jpg", 
"1893-Jane Avril-Henri Toulouse Lautrec-Art Nouveau.jpg", 
"1893-Vignetta-Henri Van De Velde-Jugendstil.jpg", 
"1894 ca-Incisione Per IV volume del periodico  The Yellow Book-Aubrey Beardsley-Art Nouveau.jpg", 
"1894-Century Font-Linn Boyd Benton-Liberty.jpg", 
"1894-Copertina per La Revue Blanche-Pierre Bonnard-Art Nouveau.jpg", 
"1894-copertina per Oscar Wilde, The Sphinx-Charles Ricketts-Art Nouveau.jpg", 
"1894-Copertina Rivista-Edward Penfield-Art Nouveau.jpg", 
"1894-Copertina Rivista-Will Bradley-Art Nouveau.jpeg", 
"1894-Eldorado-Jules Cheret-Art Nouveau.jpg", 
"1894-Illustrazione per l_opera di Salome (1 versione)-Aubrey Beardsley-Art Nouveau.jpg", 
"1894-Illustrazione per l_opera di Salome (2 versione)-Aubrey Beardsley-Art Nouveau.jpg", 
"1894-Manifesto per Salon des Cent Parigi-Eugène Grasset-Art Nouveau.jpg", 
"1894-Manifesto pubblicitario-Théopile Alexandre Steinlen-Art Nouveau.jpeg", 
"1894-Manifesto-Beggarstaff Brothers-Art Nouveau.jpg", 
"1894-Palais De Glace-Jules Cheret-Art Nouveau.jpg", 
"1894-The Serpentine Dancer-Will Bradley-Art Nouveau.jpg", 
"1895 ca-Isolde, litografia-Aubrey Beardsley-Art Nouveau.jpeg", 
"1895 ca-Manifesto-Will Bradley-Art Nouveau.jpeg", 
"1895-Copertina -Will Bradley-Art Nouveau.jpeg", 
"1895-Copertina-Franz Von Stuck-Jugendstil.jpg", 
"1895-Manifesto Pubblicitario-Jan Toorop-Nieuwe Kunst Olandese.jpg", 
"1895-Manifesto-Beggarstaff Brothers-Art Nouveau.jpg", 
"1895-Manifesto-Will Bradley-Art Nouveau.jpeg", 
"1895-Pagina di calendario, Litografia-T. Willem Nieuwenhuis-Art Nouveau.jpg", 
"1896-Copertina  Simplicissimus-Thomas T.Heine-Jugendstil.jpg", 
"1896-Frontespizio per l_opera Nimphidia and the Muse_s Elizium-Charles Ricketts-Art Nouveau.jpg", 
"1896-Frontespizio per Venus and Tannhauser-Aubrey Beardsley-Art Nouveau.jpeg", 
"1896-Manifesto per lo spettacolo Gismonda di Sarah Bernhardt-Alphonse Mucha-Art Nouveau.jpg", 
"1896-Manifesto per l_istituto d_arte di Glasgow-Margaret e Frances Macdonald con Herbert McNair-Art Nouveau-.jpg", 
"1896-Manifesto-Théopile Alexandre Steinlen-Art Nouveau.jpeg", 
"1896-Pagina di Jugend-Otto Eckmann-Jugendstil.jpg", 
"1896-Pagina di Works of Geoffrey-William Morris-Arts And Crafts.jpg", 
"1896-Palais De Glace-Jules Cheret-Art Nouveau.jpg", 
"1896-Progetto di Copertina per Verses di Ernest Dowson-Aubrey Beardsley-Art Nouveau.jpg", 
"1896-pubblicità per le sigarette Job-Alphonse Mucha-Art Nouveau.jpg", 
"1896-Suzy Deguez-Eugène Grasset-Art Nouveau.jpeg", 
"1896-Troupe De M.lle Églantine-Henri Toulouse Lautrec-Art Nouveau.jpg", 
"1897-Caccia alla volpe nella campagna Romana-Giuseppe Primoli-Fotografia.jpg", 
"1897-Copertina di Jugend-Hans Christiansen-Jugendstil.jpg", 
"1897-Manifesto-Thomas T.Heine-Jugendstil.jpg", 
"1898-copertina primo numero Ver Sacrum-Alfred Roller-Secessione Viennese.jpg", 
"1898-Font-Eugène Grasset-Art Nouveau .jpg", 
"1898-Illustrazione per Ver Sacrum, Litografia-Koloman Moser-Secessione Viennese.jpg", 
"1898-manifesto per la prima Esposizione della secessione Viennese-Gustav Klimt-Secessione Viennese .jpg", 
"1898-Manifesto per lo spettacolo Medea di Sarah Bernhardt-Alphonse Mucha-Art Nouveau.jpg", 
"1898-Manifesto-Felix Vallotton-Art Nouveau.jpg", 
"1898-Manifesto-Henri Van De Velde-Jugendstil.jpeg", 
"1898-Scena Parigina-Eugene Atget-Fotografia.jpg", 
"1899-Manifesto per le Frou Frou-Leonetto Cappiello-Liberty.jpeg", 
"1899-Manifesto per Tosca-Adolfo Hohestein-Liberty.jpg", 
"1899-Sudi di grafica editoriale-Walter Crane-Arts And Crafts.jpg", 
"1900 ca-Vignetta, xilografia-Will Bradley-Art Nouveau.jpg", 
"1900-Disegno per Line and Form-Walter Crane-Liberty.jpg", 
"1900-Font-Otto Eckmann-Jugendstil.jpg", 
"1900-Loie Fuller-Manuel Orazi-Art Nouveau.jpg", 
"1900-Marchio AEG-Otto Eckmann-Jugendstil.jpg", 
"1900-Studio di intarsi e caratteri Tipografici-Koloman Moser-Secessione Viennese.jpg", 
"1901-Copperplate Font-Frederic Goudy-Liberty.jpg", 
"1901-Font-Georges Auriol-Art Nouveau.jpg", 
"1901-Manifesto-Leonetto Cappiello-Liberty.jpeg", 
"1901-Menù per il locale di Glasgow The White Cockode-Margaret Macdonald-Art Nouveau.jpg", 
"1901-Pagine Ver Sacrum-Koloman Moser-Secessione Viennese.jpg", 
"1901-tavola della serie FlachenMuster, con disegni per carte da parati 2-Secessione Viennese.jpg", 
"1901-tavola della serie FlachenMuster, con disegni per carte da parati-Secessione Viennese.jpg", 
"1902-Copertina della rivista Leslie_s Weekly-Rivista Moderna.jpg", 
"1902-copertina volume-Koloman Moser-Secessione Viennese.jpg", 
"1902-Manifesto XIII mostra Secessione-Koloman Moser-Secessione Viennese.jpg", 
"1902-Monogramma-Koloman Moser-Secessione Viennese.jpg", 
"1902-The Flatiron Building-Edward Steichen-Fotografia.jpg", 
"1903-Ex Libris-Koloman Moser-Secessione Viennese.jpg", 
"1903-vignetta per Ver Sacrum-Josef Hoffmann-Secessione Viennese.jpg", 
"1904-Frontespizio-Adolfo De Carolis-Liberty.jpeg", 
"1904-Manifesto per Chocolat Klaus-Leonetto Cappiello-Liberty.jpeg", 
"1905 Eugène Grasset-1896-Otto Eckmann-Art Nouveau.jpg", 
"1905-1907-Manifesto-Ernst Ludwig Kirchner-Espressionismo.jpg", 
"1905-Franklin Gothic Font-Morris Fuller-Liberty.jpg", 
"1905-manifesto per la Wiener-Werkstatte-Josef Hoffmann-Secessione Viennese.jpg", 
"1905ca-Pagina Calligrafica-Edward Johnston-Arts And Crafts.jpg", 
"1906-Manifesto per Maurin Quina-Leonetto Cappiello-Liberty.jpeg", 
"1906-Veduta di New York-Edward Steichen-Fotografia.jpg", 
"1907-1908-Calendario e pagina di rivista-Peter Behrens-Deutscher Werkbund.jpg", 
"1907-manifesto per Cabaret Fledermaus-Berthold Loffler-Secessione Viennese.jpg", 
"1908-Arrivo maratona Olimpica di Londra-Anonimo-Fotografia.jpg", 
"1908-copertina catalogo AEG-Peter Behrens-Deutscher Werkbund.jpg", 
"1908-Copertina e retro catalogo AEG-Peter Behrens-Deutscher Werkbund.jpg", 
"1908-Doppia pagina della rivista Le Vie au Grand Air-Rivista Moderna.jpg", 
"1908-Font per AEG-Peter Behrens-Art Nouveau.jpg", 
"1908-Frontespizio per Ecce Homo di Nietzsche-Henri Van De Velde-Jugendstil.jpeg", 
"1908-Illustrazione per Nibelungen, doppia pagina-Carl Otto Czeschka-Secessione Viennese.jpg", 
"1908-Manifesto per i magazzini Mele di Napoli-Marcello Dudovich-Liberty.jpeg", 
"1908-Manifesto Pubblicitario-Ludwig Hohlwein-Jugendstil.jpeg", 
"1908-manifesto-Berthold Loffler-Secessione Viennese.jpg", 
"1908-Manifesto-Lucian Bernhard-Jugendstil.jpeg", 
"1908-Manifesto-Oscar Kokoschka-Secessione Viennese.jpg", 
"1908-Marchio AEG-Peter Berhens-Deutscher Werkbund.jpg", 
"1908-Variante Marchio AEG-Peter Berhens-Deutscher Werkbund.jpg", 
"1908-Vetreria-Lewis W. Hine-Fotografia.jpg", 
"1909-Manifesto per Thermogène-Leonetto Cappiello-Liberty.jpeg", 
"1910-Doppia pagina di L_Assiette au Beurre, Litografie a colori-Rivista Moderna.jpg", 
"1910-manifesto AEG-Peter Behrens-Deutscher Werkbund.jpg", 
"1910-manifesto per il settore lampade della AEG-Peter Behrens-Deutscher Werkbund.jpg", 
"1910-Manifesto per una Esposizione-Max Pechstein-Espressionismo.jpg", 
"1910-Manifesto-Julius Klinger-Jugendstil.jpg", 
"1910-Manifesto-Ludwig Hohlwein-Jugendstil.jpeg", 
"1911-Dattilografa-Anton Giulio Bragaglia-Fotografia.jpg", 
"1911-Fotogramma-El Lissitzky-Fotografia.jpg", 
"1911-Manifesto 2-Hans R. Erdt-Jugendstil.jpeg", 
"1911-Manifesto-Hans R. Erdt-Jugendstil.jpeg", 
"1911-Manifesto-Oscar Kokoschka-Espressionismo.jpg", 
"1912-Copertina-Umberto Boccioni-Futurismo.jpg", 
"1912-L_illustration-Rivista moderna.jpeg", 
"1912-Manifesto-Lucian Bernhard-Jugendstil.jpg", 
"1912-Marchio ufficiale AEG-Peter Berhens-Deutscher Werkbund.png", 
"1913-Catalogo della mostra Secessione Romana-Aleardo Terzi-Liberty.jpg", 
"1913-Manifesto-Julius Gipkens-Jugendstil.jpg", 
"1914-Bozzetto di scena-Giacomo Balla-Futurismo.jpeg", 
"1914-Copertina-Filippo T. Marinetti-Futurismo.jpeg", 
"1914-Illustrazione per D_Annunzio in La lettura-Duilio Cambellotti-Sotto-1906-Vignetta per pubblicità-Aleardo Terzi-Liberty.jpg", 
"1914-Manifesto per Cabiria-Leopoldo Metlicovitz-Liberty.jpeg", 
"1914-manifesto per casa Gaumont-Achille L. Mauzan-Liberty.jpeg", 
"1914-Manifesto per Dentol-Aleardo Terzi-Liberty.jpg", 
"1914-Manifesto-E.V. Kealey-Grafica e guerra.jpeg", 
"1914-Pagina Zang Tumb Tumb-Filippo T. Marinetti-Futurismo.jpeg", 
"1914-Parolalibera-Francesco Cangiullo-Futurismo.jpeg", 
"1914ca-manifesto per il film La maschera tragica-Achille L. Mauzan-Liberty.jpg", 
"1915-Autoritratto-Corrado Govoni-Futurismo.jpg", 
"1915-Manifesto per la campagna militare-Lucian Bernhard-Grafica e guerra.jpg", 
"1915-pagina di Bif _ Zf + 18-Ardengo Soffici-Futurismo.jpeg", 
"1916-Manifesto per una mostra personale-Bart van der Leck-Neoplasticismo.jpeg", 
"1917-Copertina De Stijl-Vilmos Huszar-Neoplasticismo.jpeg", 
"1917-Frontespizio del periodico Dada-Tristan Tzara-Dada.jpg", 
"1917-manifesto a favore dell_arruolamento-James Montgomery Flagg-Grafica e guerra.jpg", 
"1917-Manifesto per la marina tedesca-Hans R. Erdt-Grafica e guerra.jpeg", 
"1917-Manifesto per prestito di guerra-Achille L. Mauzan-Grafica e guerra.jpg", 
"1918-Calligrammes-Guillaume Apollinaire-Dada.jpg", 
"1918-Composizione (Martello e Sega) in De Stijl n3-Vilmos Huszar-De Stijl.jpg", 
"1918-Particolare manifesto per Daily Herald-E. McKnight Kauffer-Art Déco.jpg", 
"1919-Alfabeto Sperimentale-Theo Van Doesburg-De Stijl.png", 
"1919-Copertina Wendingen-J. Luger-Neoplasticismo.jpg", 
"1919-Manifesto di propaganda anticapitalista-D. Moor-Avanguardie russe.jpg", 
"1919-manifesto Insinua nei bianchi il cuneo rosso-El Lissitzky-Avanguardie Russa.jpg", 
"1919-pagina Les mots en liberté futuriste-Filippo T. Marinetti-Futurismo.jpeg", 
"1919-Primo Sigillo del Bauhaus-Karl Peter Rohl-Bauhaus.jpg", 
"1920 ca-Copertina di Vogue-Georges Lepape-Art Déco.jpg", 
"1920-Frontespizio del racconto Dei due quadrati-El Lissitzky-Avanguardie Russa.jpeg", 
"1920-Giornale Murale-Vladimir Majakovskij-Avanguardie russe.jpeg", 
"1920-Tatlin in casa sua-Raoul Hausmann-Dada.jpg", 
"1921-22-Les Champs Delicieux-Man Ray-Fotografia.jpg", 
"1921-Manifesto per Bitter Campari-Enrico Sacchetti-Liberty.jpeg", 
"1921-Manifesto per Bitter Campari-Leonetto Cappiello-Liberty.jpeg", 
"1921-Manifesto per Max Mayer-Aleardo Terzi-Liberty.jpeg", 
"1922-Copertina di Rivista-Laszlo Moholy-Nagy-Neoplasticismo.jpeg", 
"1922-Copertina rivista Vesc (Objet, Gegenstand)-El Lissitzky-Neoplasticismo.jpeg", 
"1922-De Stijl Nuova Impostazione Grafica-Theo Van Doesburg-Neoplasticismo.jpeg", 
"1922-Pagina della rivista Mecano-Theo Van Doesburg-De Stijl.jpeg", 
"1922-Sigillo ufficiale del Bauhaus-Oskar Schlemmer-Bauhaus.jpg", 
"1923 ca-Pneumatik, Fotomontaggio-Laszlo Moholy-Nagy-Bauhaus.jpeg", 
"1923-Cartolina pubblicitaria-Piet Zwart-Neoplasticismo.jpg", 
"1923-Copertina di catalogo-Herbert Bayer-Bauhaus.jpeg", 
"1923-Copertina n1 rivista LEF-Aleksandr Rodcenko-Avanguardie russe.jpeg", 
"1923-Copertina Pro Eto di Majakovskij-Aleksandr Rodcenko-Avanguardie russe.jpeg", 
"1923-Manifesto esposizione Bauhaus-Joost Schmidt-Bauhaus.jpeg", 
"1923-Manifesto pubblicitario per Mospoligraf-Aleksandr Rodcenko-Avanguardie russe.jpeg", 
"1923-Pagina dell_opera Per La Voce di Majakovskij-El Lissitzky-Avanguardie Russa.jpg", 
"1923ca-Manifesto-Marcello Dudovich-Liberty.jpeg", 
"1924 ca-Violon d_Ingres-Man Ray-Fotografia.jpg", 
"1924-Copertina di Mertz n 8-9-Kurt Schwitters-Dada.jpg", 
"1924-Copertina per raccolta di poesie-Aleksandr Rodcenko-Avanguardie russe.jpeg.jpg", 
"1924-Copertina per Un Bauhausbuch-Bauhaus.jpeg", 
"1924-Copertina rivista LEF-Aleksandr Rodcenko-Avanguardie russe.jpeg", 
"1924-Doppia pagina per Tne Next Call-Hendrik N. Werkman-Neoplasticismo.jpg", 
"1924-Frontespizio della cartella Artisti italiani e russi-Lyonel Feininger-Bauhaus.jpg", 
"1924-manifesto Il Nuovo Teatro Futurista-Fortunato Depero-Secondo Futurismo.jpg", 
"1924-Manifesto pubblicitario per Gosizdat-Aleksandr Rodcenko-Avanguardie russe.jpeg.jpeg", 
"1924-Manifesto pubblicitario per Pelikan-El Lissitzky-Avanguardie Russe.jpg", 
"1924-Progetto di Edicola-Bauhaus.jpeg", 
"1925 ca-Cartolina pubblicitaria vendita prodotti del Bauhaus-Joost Schmidt-Bauhaus.jpg", 
"1925-Copertina catalogo NKF-Piet Zwart-Neoplasticismo.jpg", 
"1925-DX, Doppia Pagina da Malerei,Fotografie,Film-Laszlo Moholy-Nagy-Bauhaus.jpeg", 
"1925-manifesto per il quotidiano L_Intransigeant-Cassandre-Art Déco.jpg", 
"1925-manifesto per music hall-Paul Colin-Art Déco.jpeg", 
"1925-manifesto-Cassandre-Art Déco.jpg", 
"1925-Pagina Pubblicitaria NKF-Piet Zwart-Neoplasticismo.jpg", 
"1925-Progetto per un alfabeto universale-Herbert Mayer-Bauhaus.jpg", 
"1925-Programma didattico Bauhaus-Bauhaus.jpg", 
"1925-Scala Antincendio-Aleksandr Rodcenko-Fotografia.jpg", 
"1925-Universal Type-Herbert Mayer-Bauhaus.jpg", 
"1926-27-Pubblicità per Campari-Fortunato Depero-Secondo Futurismo.jpeg", 
"1926-Copertina rivista Offset-Joost Schmidt-Bauhaus.jpeg", 
"1926-manifesto per il film Metropolis di Fritz Lang-Schulz-Neudamm-Art Déco.jpeg", 
"1926-Manifesto per una conferenza di Hans Poelzig-Herbert Mayer-Bauhaus.jpg", 
"1926-Manifesto Squisito al Selz-Fortunato Depero-Secondo Futurismo.jpeg", 
"1926-Uomo-matita impennacchiato-Fortunato Depero-Secondo Futurismo.jpeg", 
"1927 ca-Balconi-Laszlo Moholy-Nagy-Fotografia.jpeg", 
"1927 ca-Kameralose Aufnahme-Laszlo Moholy-Nagy-Fotografia.jpeg", 
"1927-1 manifesto per le ferrovie-Cassandre-Art Déco.jpg", 
"1927-Carattere Bifur-Cassandre-Art Déco.jpeg", 
"1927-Copertina dell_opuscolo della scuola-Bauhaus.jpg", 
"1927-Copertina per l_almanacco del Vchutemas-El Lissitzky-Avanguardie Russa.jpg", 
"1927-Libro bullonato per Dinamo-Azari-Fortunato Depero-Secondo Futurismo.jpeg", 
"1927-manifesto per le ferrovie-Cassandre-Art Déco.jpg", 
"1927-manifesto-Cassandre-Art Déco.jpg", 
"1928-Bozzetto per il libro Le Quattro Operazioni-El Lissitzky-Avanguardie Russa.jpg", 
"1928-Copertina primo numero rivista Bauhaus-Bauhaus.jpg", 
"1928-manifesto-Ercole Giommi-Secondo Futurismo.jpeg", 
"1928-manifesto-Severo Pozzati (Sepo)-Art Déco.jpeg", 
"1928-Ombra sulle scale-Herbert Bayer-Fotografia.jpg", 
"1928-Pagina interna del catalogo NKF-Piet Zwart-Neoplasticismo.jpg", 
"1929-Brochure promozionale carattere Broadway-Morris Fuller Benton-Art Déco.jpeg", 
"1929-Manifesto per Buitoni-Federico Seneca-Secondo Futurismo.jpeg", 
"1929-Pagine interne di De Wapens Neder-Paul Schuitema-Neoplasticismo.jpg", 
"1929-Progetto per copertina Vogue-Fortunato Depero-Secondo Futurismo.jpeg", 
"1930 ca- Effetti di trasparenza-Walter Peterhans-Fotografia.jpg", 
"1930 ca-Studio realizzato al Bauhaus-Eugen Batz-Bauhaus.jpg", 
"1930-Copertina Vanity Fair-Fortunato Depero-Secondo Futurismo.jpeg", 
"1930-Manifesto per una Esposizione-Herbert Bayer-Bauhaus.jpeg", 
"1930-progetto per padiglione pubblicitario-Fortunato Depero-Secondo Futurismo.jpeg", 
"1930-Scala-Aleksandr Rodcenko-Fotografia.jpg", 
"1931-Bozzetto per il frontespizio del Numero Unico Futurista Campari-Fortunato Depero-Secondo Futurismo.jpg", 
"1931-Campagna Promossa dalle Poste Olandesi a favore dei disabili-Gerard Kiljan-Neoplasticismo.gif", 
"1931-Catalogo per le carte da parati del Bauhaus-Joost Schmidt-Bauhaus.jpeg", 
"1931-Copertina e retro di Wendingen-El Lissitzky-Neoplasticismo.jpg", 
"1931-Copertina per Harper_s Bazar-Erté-Art Déco.jpeg", 
"1931-Copertina Rivista-Piet Zwart-Neoplasticismo.jpg", 
"1931-Copertina-S. L. Schwarz-Neoplasticismo.jpg", 
"1931-manifesto per Campari-Marcello Nizzoli-Secondo Futurismo.jpeg", 
"1931-Manifesto per la città di Dessau-Joost Schmidt-Bauhaus.jpeg", 
"1931-manifesto per una compagnia di navigazione-Cassandre-Art Déco.jpg", 
"1931-manifesto perla Fiera di Milano-Marcello Nizzoli-Secondo Futurismo.jpeg", 
"1931-Pagina di catalogo per Drukkeij Trio-Piet Zwart-Neoplasticismo.jpg", 
"1931-Pagina di catalogo-Piet Zwart-Neoplasticismo.jpg", 
"1932-Autoritratto-Herbert Bayer-Fotografia.jpg", 
"1932-Einsamer Grossstader-Herbert Bayer-Fotografia.jpg", 
"1932-Manifesto Poste Olandesi-Piet Zwart-Neoplasticismo.jpg", 
"1932-manifesto-Cassandre-Art Déco.jpg", 
"1932-Trittico di manifesti per Dubonnet-Cassandre-Art Déco.jpg", 
"1933-annuncio dello studio Boggeri-Antonio Boggeri-Studio Boggeri.jpeg", 
"1933-Catalogo della fonderia Berthold per il Bayer Type-Herbert Bayer-Bauhaus.jpeg", 
"1933-Logotipo per lo Studio Boggeri-Deberny e Peignot-Studio Boggeri.png", 
"1933-manifesto per l_acquario del Principato di Monaco-Jean Carlu-Art Déco.jpg", 
"1934-copertina per il calendario Olivetti-Xanti Shawinsky-Studio Boggeri.jpg", 
"1934-Manifesto per il caffè Illy (Studio Boggeri)-Xanti Schawinsky-Studio Boggeri.jpeg", 
"1934-manifesto per un quotidiano-Mario Sironi-Secondo Futurismo.jpg", 
"1934-manifesto-E. McKnight Kauffer-Art Déco.jpg", 
"1934-Ragazza con la Leica-Aleksandr Rodcenko-Fotografia.jpg", 
"1935-Copertina Campo Grafico-Luigi Veronesi-Campo Grafico.jpeg", 
"1935-Manifesto per Adrianol-Herbert Bayer-Bauhaus.jpeg", 
"1935-manifesto per un produttore di vini-Cassandre-Art Déco.jpg", 
"1935-Manifesto-Wim Brusse-Neoplasticismo.jpg", 
"1935-Progetto per un manifesto-Cassandre-Art Déco.jpg", 
"1936-Copertina Casabella n.102-103-Casabella.jpeg", 
"1936-Copertina-Herbert Bayer-Bauhaus.jpeg", 
"1937-copertina di Campo Grafico-C. Dradi e A. Rossi-Campo Grafico.jpeg", 
"1937-manifesto-Paul Colin-Art Déco.jpeg", 
"1940-annuncio pubblicitario-Max Huber-Studio Boggeri.jpeg", 
"1940-copertina opuscolo promozionale-Max Huber-Studio Boggeri.jpeg", 
"1940-Restylng pacchetto Lucky Strike-Raymond Loewy-Primi Packaging.jpeg", 
"1942-manifesto-Jean Carlu-Art Déco.jpeg", 
"1960-63-monogramma e logotipo per Yves Saint-Laurent-Cassandre-Art Déco.png", 
"1962-Composizione-Victor Vasarely-Gestaltpsychologie.jpg"];

var a, b, c = 0;
var citta_industriali, ferro_e_vetro, arts_and_craft, nuovo_mondo, scuola_di_chicago, art_nouveau;

function archFunction()
    {      
        a = Math.floor(Math.random() * imgArchLink.length);
        document.getElementById("imgArch").src = "img/Arch/" + imgArchLink[a];
        document.getElementById("archButtonSpoiler").hidden = false;
        document.getElementById("archRandom").innerHTML = "Nuova immagine";
        document.getElementById("spoilerArch").innerHTML = "";
    }
function archFunctionSpoiler()
    {
        document.getElementById("spoilerArch").innerHTML = imgArchLink[a].replace(".jpg", "");
    }  

    function desFunction()
    {   
        b = Math.floor(Math.random() * imgDesLink.length);
        document.getElementById("imgDes").src = "img/Des/" + imgDesLink[b];
        document.getElementById("desButtonSpoiler").hidden = false;
        document.getElementById("desRandom").innerHTML = "Nuova immagine";
        document.getElementById("spoilerDes").innerHTML = "";        
    }
function desFunctionSpoiler()
    {
        document.getElementById("spoilerDes").innerHTML = imgDesLink[b].replace(".jpg", "");
    }  

function GrafFunction()
    {   
        c = Math.floor(Math.random() * imgGrafLink.length);
        document.getElementById("imgGraf").src = "img/Graf/" + imgGrafLink[c];
        document.getElementById("grafButtonSpoiler").hidden = false;
        document.getElementById("grafRandom").innerHTML = "Nuova immagine";
        document.getElementById("spoilerGraf").innerHTML = "";
    }
function GrafFunctionSpoiler()
    {
        document.getElementById("spoilerGraf").innerHTML = imgGrafLink[c].replace(".jpg", "");
    }  